/** Mapa extensión → lenguaje + color (subconjunto de github-linguist). */

export interface LangDef {
  name: string;
  color: string;
}

const L = (name: string, color: string): LangDef => ({ name, color });

export const EXT_TO_LANG: Record<string, LangDef> = {
  ".ts": L("TypeScript", "#3178c6"),
  ".tsx": L("TypeScript", "#3178c6"),
  ".mts": L("TypeScript", "#3178c6"),
  ".cts": L("TypeScript", "#3178c6"),
  ".js": L("JavaScript", "#f1e05a"),
  ".jsx": L("JavaScript", "#f1e05a"),
  ".mjs": L("JavaScript", "#f1e05a"),
  ".cjs": L("JavaScript", "#f1e05a"),
  ".py": L("Python", "#3572A5"),
  ".rs": L("Rust", "#dea584"),
  ".go": L("Go", "#00ADD8"),
  ".java": L("Java", "#b07219"),
  ".kt": L("Kotlin", "#A97BFF"),
  ".cs": L("C#", "#178600"),
  ".cpp": L("C++", "#f34b7d"),
  ".cc": L("C++", "#f34b7d"),
  ".cxx": L("C++", "#f34b7d"),
  ".hpp": L("C++", "#f34b7d"),
  ".c": L("C", "#555555"),
  ".h": L("C", "#555555"),
  ".rb": L("Ruby", "#701516"),
  ".php": L("PHP", "#4F5D95"),
  ".swift": L("Swift", "#F05138"),
  ".scala": L("Scala", "#c22d40"),
  ".dart": L("Dart", "#00B4AB"),
  ".lua": L("Lua", "#000080"),
  ".r": L("R", "#198CE7"),
  ".jl": L("Julia", "#a270ba"),
  ".ex": L("Elixir", "#6e4a7e"),
  ".exs": L("Elixir", "#6e4a7e"),
  ".erl": L("Erlang", "#B83998"),
  ".hs": L("Haskell", "#5e5086"),
  ".ml": L("OCaml", "#ef7a08"),
  ".zig": L("Zig", "#ec915c"),
  ".vue": L("Vue", "#41b883"),
  ".svelte": L("Svelte", "#ff3e00"),
  ".astro": L("Astro", "#ff5a03"),
  ".html": L("HTML", "#e34c26"),
  ".htm": L("HTML", "#e34c26"),
  ".css": L("CSS", "#663399"),
  ".scss": L("SCSS", "#c6538c"),
  ".sass": L("SCSS", "#c6538c"),
  ".less": L("Less", "#1d365d"),
  ".sql": L("SQL", "#e38c00"),
  ".sh": L("Shell", "#89e051"),
  ".bash": L("Shell", "#89e051"),
  ".ps1": L("PowerShell", "#012456"),
  ".psm1": L("PowerShell", "#012456"),
  ".bat": L("Batchfile", "#C1F12E"),
  ".cmd": L("Batchfile", "#C1F12E"),
  ".yml": L("YAML", "#cb171e"),
  ".yaml": L("YAML", "#cb171e"),
  ".json": L("JSON", "#292929"),
  ".toml": L("TOML", "#9c4221"),
  ".md": L("Markdown", "#083fa1"),
  ".mdx": L("Markdown", "#083fa1"),
  ".tf": L("Terraform", "#844FBA"),
  ".proto": L("Protobuf", "#4a76c6"),
  ".graphql": L("GraphQL", "#e10098"),
  ".sol": L("Solidity", "#AA6746"),
  ".nim": L("Nim", "#ffc200"),
  ".clj": L("Clojure", "#db5855"),
  ".fs": L("F#", "#b845fc"),
  ".groovy": L("Groovy", "#4298b8"),
  ".pl": L("Perl", "#0298c3"),
  ".m": L("Objective-C", "#438eff"),
  ".ipynb": L("Jupyter", "#DA5B0B"),
  ".glsl": L("GLSL", "#5686a5"),
  ".frag": L("GLSL", "#5686a5"),
  ".vert": L("GLSL", "#5686a5"),
  ".wgsl": L("WGSL", "#1a5e9a"),
};

/** Ficheros que no cuentan como "código" a efectos de mezcla de lenguajes. */
export const IGNORED_FILES = new Set([
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "bun.lockb",
  "cargo.lock",
  "poetry.lock",
  "uv.lock",
  "composer.lock",
  "gemfile.lock",
]);
